### ISSUE TITLE
Binding object({"id":13,"code":"XXX"}) with bindValue is not allowed

### ISSUE THREAD

**Issue by tsetrest** [ng-select/ng-select#439] opened 2018-04-10 14:07 UTC
Please fill below information if issuing a bug report. 
### Expected behaviour
Describe how you think it should work
 <ng-select [items]="data" 
                bindLabel="code" 
                bindValue="form.get('data')" [multiple]="true" placeholder="Select data" 
                clearAllText="Clear" formControlName="data"> 
                </ng-select>
### Actual behaviour
Describe how it actually works or create example using [Plunker](https://plnkr.co/edit/hjZX6W?p=preview) issue template 
### More Info
ng-select version: [INSERT HERE]

browser: [INSERT BROWSER INFO HERE]

reproducible in demo page: [YES/NO]

**Comment by anjmao** [comment] 2018-04-10 14:40
Duplicate of https://github.com/ng-select/ng-select/issues/417

**Closed by anjmao** 2018-04-10 14:40 UTC
