### ISSUE TITLE
Move Cursor through arrow keys or set cursor position by clicking through mouse when option is selected 

### ISSUE THREAD

**Issue by monis01** [ng-select/ng-select#1201] opened 2019-05-31 09:02 UTC
**Describe the bug**
When we select any option in ng-select and tries to move cursor through arrow keys Or tries to reset cursor position but cursor does not move. It is glued to initial starting position.

**Reproducbile example**
Can be seen in [demo example](https://ng-select.github.io/ng-select#/data-sources)

**Expected behavior**
After selecting an option if able to move the cursor back and forth through cursor; if user can move cursor and the easily type that ell show matched options.

**Screenshots**
![ng-select](https://user-images.githubusercontent.com/7036532/58694374-790eb300-83b0-11e9-84a7-ec5b0341ec6e.png)
Cannot move the cursor; 

**Additional context**
By the way is this context to be considered ?

**Comment by varnastadeus** [comment] 2019-05-31 10:21
I think this is duplicate of https://github.com/ng-select/ng-select/issues/1156

**Closed by varnastadeus** 2019-05-31 10:21 UTC
