### ISSUE TITLE
Close the option list when it lost focus

### ISSUE THREAD

**Issue by shipon-eye** [ng-select/ng-select#55] opened 2017-10-01 10:45 UTC
![untitled](https://user-images.githubusercontent.com/4049153/31053838-c3d504d8-a6c7-11e7-97d7-a1134f9bb03d.png)

Thanks for the nice component and for the frequent updates.
By the way, I am using the ng-select component in one of my ionic 3 project.
In my project, i have found that if the "[multiple]="true"", the option list (drop down) doesn't close when I move focus to next component by pressing TAB key or even mouse click. Option list should close when ng-select component lost the focus. Please check whether it is my project specific problem or bug in ng-select.

thanks

**Comment by anjmao** [comment] 2017-10-01 12:03
@shipon-eye Are you using 0.2.0 npm version? I cant reproduce it in demo page. For me dropdown is closes on blur and on tab click.

**Comment by shipon-eye** [comment] 2017-10-01 19:52
My npm version is 3.10.10. By the way, I am using Visual Studio 2017 Community version to develop Ionic 3 Hybrid + PWA app. following are the ionic and angular configs:
"@angular/common": "4.3.5",
    "@angular/compiler": "4.3.5",
    "@angular/compiler-cli": "4.3.5",
    "@angular/core": "4.3.5",
    "@angular/forms": "4.3.5", 
 "ionic-angular": "3.7.1",
    "ionic-native": "^2.9.0"

**Comment by varnastadeus** [comment] 2017-10-02 08:16
@shipon-eye update ng-select package to latest version, this issue is already fixed there.

**Comment by Eretik** [comment] 2017-10-03 19:35
@anjmao, @varnastadeus Unfortunately, I can reproduce this bug it on last build. ng-select element lose class 'focused' but not 'opened'. The only way to close it - set focus to other input element on the page and click somewhere out of this input to fire 'blur' event.

**Comment by varnastadeus** [comment] 2017-10-04 08:25
@Eretik can you add more description how can I reproduce it?

**Comment by varnastadeus** [comment] 2017-10-04 16:00
@shipon-eye @Eretik Try updating to latest version and check if it still reproducible. #67 should fix that

**Closed** 2017-10-13 17:28 UTC
Labels: duplicate

**Comment by xigolle** [comment] 2018-03-19 15:11
I am not sure if this is the way to bump this thread.
But I have the same problem that when I open a dropdown and select another input or at least lose focus on the dropdown it keeps open. 
I already saw that updating to the newest version would resolve this. But unfortunally it didn't (using V 30.1). 

Somebody might have an idea what could be the issue?

**Comment by YanFChen** [comment] 2018-04-03 22:11
having the same issue here with dropdowns where when expanded, it does not close unless I hit 'ESC' on the keyboard. Clicking elsewhere on the page or selecting an option does not close the dropdown.
