### ISSUE TITLE
ng-select not able to edit text after Item selection

### ISSUE THREAD

**Issue by sanmscse** [ng-select/ng-select#1088] opened 2019-03-06 04:34 UTC
Hi,
I am using Angular 5 with "@ng-select/ng-select": "^1.5.2"

I had an issue with ng-select text focus and edit text after selected item.

For ex i searched "Test12" first, then i've to choose "test31" in this case i can't clear last two characters.
For change search term i've to clear whole text and retype again for new search.

Please provide some guidance on how to achieve this using ng-select
@varnastadeus , @Coveralls

Thanks,
saravanan

**Comment by varnastadeus** [comment] 2019-03-10 11:12
create reproducible example

**Comment by sillybutt0** [comment] 2019-03-25 02:31
Have the same issue, which is critical in my project. Didn't find solution in sources by myself. Don't see necessity in reproducible example because this issue has everyone, you can try here: https://ng-select.github.io/ng-select/

Case again:
1. Write "Hello, Jack"
2. Want to change 'Jack' to 'Joe'
3. You have to type in 'Hello, Joe' from the beginning to change value to what you want

So in case if you search something long and make a typo (a phone number e.g.) - you have to write it again all the way, since you unfocus the field for the first time.

**Comment by sillybutt0** [comment] 2019-03-25 07:44
@sanmscse I made a quick solution, have a look:
Add this code to toggleItem and onInputBlur handlers:
`
if (this.element.querySelector("input[role='combobox']")) {
   this.element.querySelector("input[role='combobox']").value = '';
 }`

Add this to onInputFocus handler:
`
if (this.element.querySelector("input[role='combobox']") && this.selectedItems.length) {
   this.element.querySelector("input[role='combobox']").value = this.selectedItems[0].label;
}
`

So we basically set input valueas selected object label and clear it on focus/select item. That let

**Comment by Komock** [comment] 2019-04-22 13:36
Same issue. I using ng-select as address autocomplete, address could be long string as you know, if i made mistake and left input, i should rewrite all address(
P.S: Tnx for library

**Comment by varnastadeus** [comment] 2019-05-14 13:26
closing in favor of #1156

**Closed by varnastadeus** 2019-05-14 13:26 UTC

**Comment by sanmscse** [comment] 2019-05-31 12:23
Hi @varnastadeus 
The reference #1156  is for Telerik control. But we spoke for Angular ng select.
Do we have a solution for Edit ng select  text after Item selection.

Thanks

**Comment by Komock** [comment] 2019-05-31 14:22
@sanmscse Hi. I added temporary solution for our ng-select wrapper to fix this issue. Ugly but works fine:
https://github.com/evotor/Evo-UI-Kit/blob/versions/v3/projects/evo-ui-kit/src/lib/modules/evo-autocomplete/components/evo-autocomplete.component.ts#L67
