### ISSUE TITLE
Exception when press keydown if last item was previously selected.

### ISSUE THREAD

**Issue by Serg-Mois** [ng-select/ng-select#964] opened 2018-11-23 11:26 UTC
**Describe the bug**
An exception:
vendor.js:85485 TypeError: Cannot read property 'disabled' of undefined
    at ItemsList.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.ItemsList._stepToItem (vendor.js:79426)
    at ItemsList.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.ItemsList.markNextItem (vendor.js:79193)
    at NgSelectComponent.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.NgSelectComponent._handleArrowDown (vendor.js:81247)
    at NgSelectComponent.push../node_modules/@ng-select/ng-select/fesm5/ng-select.js.NgSelectComponent.handleKeyDown (vendor.js:80470)
    at Object.eval [as handleEvent] (ng:///WbcSelectModule/WbcSelectComponent.ngfactory.js:48)
    at handleEvent (vendor.js:61028)
    at callWithDebugContext (vendor.js:62122)
    at Object.debugHandleEvent [as handleEvent] (vendor.js:61825)
    at dispatchEvent (vendor.js:58477)
    at vendor.js:58924

**To Reproduce** 
ng-select with predefined data ( e.g. data option is filled ) and multiple mode.
1. Focus control, press keyDown button - dropdown is opened.
2. focus last option via keydown and select it by enter - value is selected, dropdown is hidden.
3. Press keyDown one more time - an exception appears, dropdown is not opened.
Reproduced only when a last item was selected in dropdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/37027173/48941108-e5e95200-ef22-11e8-8871-10776f521870.png)
![image](https://user-images.githubusercontent.com/37027173/48941206-44163500-ef23-11e8-938c-5c775025fe61.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser Chrome
 - Version "2.11.1",

**Comment by varnastadeus** [comment] 2018-11-23 15:37
@Serg-Mois can you create reproducible example? can't reproduce it in demo page

**Comment by sircon** [comment] 2018-11-23 15:41
@varnastadeus I also had this before but couldn't reproduce but now I did.

*Steps to reproduce*
1) Go to the Custom server-side search in https://ng-select.github.io/ng-select#/filter
2) Write down `a` and delete it to have the whole list
3) Select `Diann Booker`
4) Press the down key

**Comment by varnastadeus** [comment] 2018-11-23 16:07
looks like this happens when `[hideSelected]="true"`

**Comment by Serg-Mois** [comment] 2018-11-23 16:12
> looks like this happens when `[hideSelected]="true"`

Yes, this I missed this option when described the issue.

**Comment by varnastadeus** [comment] 2019-06-25 17:00
I think this is fixed in the latest version

**Closed by varnastadeus** 2019-06-25 17:00 UTC
Labels: improvement
