### ISSUE TITLE
Selected value binding as Placeholder. Is there any option to binding as Input value?

### ISSUE THREAD

**Issue by salih0313** [ng-select/ng-select#324] opened 2018-03-07 09:40 UTC
Once selected the value from list, it is binding as Placeholder of input. if i want to type more from which i have typed or selected earlier, i can't. i need to type from begin. 

is there any option / setting for selected or typed value bind as Input value?

**Comment by varnastadeus** [comment] 2018-03-15 13:54
@salih0313 it is quite difficult to understand your request,  do you want to keep search term after selecting an item?

**Comment by salih0313** [comment] 2018-03-20 07:14
@varnastadeus  Selected item displaying as Placeholder. Not a as input value. 

eg, 

I have selected "Item ABC". once selected, it displaying like placeholder of the input field. 
I want to continue search term from selected item. that means "Item ABC" + "DE".  As of now, selected item displaying as placeholder of Input Field. So, i need to search from begin. Like "Item ABCDE"...

Hope, you understood.

**Comment by varnastadeus** [comment] 2018-03-21 18:31
@salih0313 you could do something like this 
https://stackblitz.com/edit/angular-ng-select-tad-rttcv5

**Comment by varnastadeus** [comment] 2018-03-21 18:33
I think this is duplicate of #276

**Closed by varnastadeus** 2018-03-21 18:33 UTC
Labels: question
