### ISSUE TITLE
not able to focus input to filter

### ISSUE THREAD

**Issue by GerritHernouTC** [ng-select/ng-select#472] opened 2018-04-18 12:45 UTC
### Expected behaviour
When I click on the input the dropdown opens and the input has focus so I can start typing

### Actual behaviour
When I click on the input the dropdown opens but the input is not focusable so it's not possible to filter.
The only way to get the focus in the input is to select an option and press the 'x' to remove the option.
[StackBlitz](https://stackblitz.com/edit/ng-select-example-9vxlnb?file=styles.scss) 

### More Info
ng-select version: 1.0.4

browser: firefox

reproducible in demo page: no

**Comment by anjmao** [comment] 2018-04-18 13:05
Hi @GerritHernouTC , it works for me in Chrome and Firefox, which Firefox version are you using?

**Comment by GerritHernouTC** [comment] 2018-04-18 13:12
firefox quantum 59.0.2 (64-bit)

IE11/chrome is working fine

**Comment by anjmao** [comment] 2018-04-18 13:45
Yep, I was able to reproduce it only on Windows, on Mac Os it is working fine.

**Comment by anjmao** [comment] 2018-04-20 05:55
@GerritHernouTC I 1.1.0 version and this issue should be fixed now.

**Closed by anjmao** 2018-04-20 05:55 UTC
Labels: bug

**Comment by varnastadeus** [comment] 2018-04-20 09:41
@GerritHernouTC can you add animated video or GIF because your example works as expected.
