### ISSUE TITLE
Input not closing on selection?

### ISSUE THREAD

**Issue by carlhussey** [ng-select/ng-select#120] opened 2017-11-07 14:51 UTC
Please fill below information if issuing a bug report. 
### Expected behaviour
When I use the typeahead or standard dropdown menu, upon selecting an option, I would expect the input to close unless multiple = true.

### Actual behaviour
Upon selecting an option, the dropdown menu stays open.

### More Info
ng-select version: 0.6.1

browser: chrome

reproducible in demo page: no

--

Is there anything that would cause such behavior from occurring?

```
<ng-select formControlName="requestor" [items]="employees" bindLabel="NTID" placeholder="Search Employees" typeToSearchText="Enter 2 characters to begin your search.."
    notFoundText="No employee records found" [typeahead]="typeahead" [clearable]="false" [(ngModel)]="employeeModel">
    <ng-template ng-label-tmp let-item="item">
        {{ item.FirstName + ' ' + item.LastName + ' ('+item.NTID+')'}}
    </ng-template>
    <ng-template ng-option-tmp let-item="item">
        <div class="row">
            <div class="col-md-1 peopleSearchPic">
                <img src="{{ PhotoURL }}{{item.QID}}.jpg" width="35px" height="45px">
            </div>
            <div class="col-md-11">
                {{ item.FirstName + ' ' + item.LastName }}
                <div class="row">
                    <div class="col-md-12">
                        <span class="smallText">NTID: {{ item.NTID }} | Location: {{ item.CenterName }}</span>
                    </div>
                </div>
            </div>
        </div>
    </ng-template>
</ng-select>
```

**Comment by carlhussey** [comment] 2017-11-07 15:10
Here is an example of it happening. I added a change event to it so I can see that there is a value assigned to it as expected. https://giphy.com/gifs/l1KdbJZv8LyP2w156/fullscreen

**Comment by varnastadeus** [comment] 2017-11-09 07:21
@carlhussey, can you make reproducible plunker or is it only reproducible on your page?

**Comment by anjmao** [comment] 2017-11-09 07:27
@carlhussey That is strange issue, can you paste what classes ng-select has when you select item. For example:
`class="typeahead searchable ng-single ng-valid ng-dirty ng-touched"`

**Comment by carlhussey** [comment] 2017-11-09 14:06
After seeing that its working in the demo, I am fully aware this is probably an issue on my end. I was hoping this may have came up before in some way so I know where to start with my code.


**Default, untouched:**

`searchable ng-single ng-untouched ng-pristine ng-invalid`

**Opened**:

`searchable ng-single ng-untouched ng-pristine ng-invalid opened`

**Value Selected:**

`searchable ng-single ng-untouched ng-dirty ng-valid opened`

**Clicked off Input:**

`searchable ng-single ng-untouched ng-dirty ng-valid`

**My Dependencies:**
```
{
  "name": "template",
  "version": "4.4.0",
  "license": "UNLICENSED",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~4.3.6",
    "@angular/common": "~4.3.6",
    "@angular/compiler": "~4.3.6",
    "@angular/core": "~4.3.6",
    "@angular/forms": "~4.3.6",
    "@angular/platform-browser": "~4.3.6",
    "@angular/platform-browser-dynamic": "~4.3.6",
    "@angular/router": "~4.3.6",
    "@ng-select/ng-select": "^0.6.1",
    "bootstrap": "~3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "~2.5.1",
    "font-awesome": "~4.7.0",
    "ngx-bootstrap": "~1.9.3",
    "rxjs": "~5.4.3",
    "web-animations-js": "^2.2.5",
    "zone.js": "~0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "~1.4.2",
    "@angular/compiler-cli": "~4.3.6",
    "@types/node": "~6.0.60",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.0"
  }
}

```

**Comment by anjmao** [comment] 2017-11-10 07:27
Hm, I see class opened is still present when value is selected, this is why you see dropdown opened. I will check code in ng-select where it is handling opened class, because it can be related to OnPush change detection strategy.

**Comment by clarkorz** [comment] 2017-11-21 16:52
my fix, works for me:
```
<ng-select ... #thisSelect (blur)="thisSelect.close()"></ng-select>
```

**Comment by varnastadeus** [comment] 2017-11-22 06:06
@clarkorz are you experiencing same issue?

**Comment by varnastadeus** [comment] 2017-11-22 18:51
@carlhussey, I have tried to reproduce your issue creating empty angular-cli project with dependencies and template you provided with no luck. There are still some things we could try:
1) Check console for errors
2) Add event listener for `onClose` event to see if it fires
3) Try to debug `close` method
4) Try to find out what causes this issue, eg.: put `ng-select` on home page to see if it works with simplest setup

**Comment by aitboudad** [comment] 2017-11-26 10:09
it's happen to me if the component is set to `OnPush` detection strategy see https://stackblitz.com/edit/angular-wnnhjl

**Comment by aitboudad** [comment] 2017-11-26 10:18
sorry I misread the issue, it's not related to this one.

**Comment by anjmao** [comment] 2017-11-26 13:09
@carlhussey I released new version `0.9.0` with another bug fix which may be related to not closing dropdown, let me know if it helped.

**Comment by carlhussey** [comment] 2017-11-28 23:27
**1) Check console for errors**
     _No errors are being thrown for this input._

**2) Add event listener for onClose event to see if it fires**
     _onClose event fires when I click on the template item, although, the input does not close._

**3) Try to debug close method**
_Unsure what you are looking for here. Upon the onClose method firing, I see that the class is being applied to the input._

`class="typeahead searchable ng-single ng-untouched ng-valid ng-dirty opened"`

One thing to note is that even though the close event is firing each time, the opened class does
 not change or get removed.

**4) Try to find out what causes this issue, eg.: put ng-select on home page, or any part of your app that has least dependencies to see if it works with simplest setup**

_I did try this as well as upgrading to the latest version, `0.10.0` and the issue still remains. I am unsure at this point what would cause it._

**Comment by varnastadeus** [comment] 2018-01-31 16:43
Closing because unable to reproduce. Feel free to open new issue if you have still have some issues.

**Closed by varnastadeus** 2018-01-31 16:43 UTC

**Comment by iamsrujal** [comment] 2020-05-01 07:43
> my fix, works for me:
> 
> ```
> <ng-select ... #thisSelect (blur)="thisSelect.close()"></ng-select>
> ```

I think the solution works for me
