### ISSUE TITLE
Dropdown menu is misplaced when page scroll bar is not visible 

### ISSUE THREAD

**Issue by ahadjithoma** [ng-select/ng-select#1404] opened 2019-10-30 08:19 UTC
**Describe the bug**
When the page has scroll bar, everything is fine. When the scroll bar is not visible, the dropdown menu is misplaced.

**Screenshots**

- This is when the page do not have scroll bar

![Annotation 2019-10-30 100237](https://user-images.githubusercontent.com/16178577/67839985-882f9380-fafd-11e9-84c0-7458d19f1b94.jpg)

- And this is with scroll bar 

![Annotation 2019-10-30 100137](https://user-images.githubusercontent.com/16178577/67839983-882f9380-fafd-11e9-9f21-c6992bac21d1.jpg)

You can see the difference clearly. 
I just upgrade to the latest version
I also tried 
```
body {
  position: relative;
}
```
in styles

**Comment by pjominet** [comment] 2019-10-30 08:30
same issue here

**Comment by varnastadeus** [comment] 2019-10-30 08:37
a reproducible example would be best

**Comment by pjominet** [comment] 2019-10-30 09:49
https://stackblitz.com/edit/angular-y51evj there :) hope that helps

**Comment by varnastadeus** [comment] 2019-10-30 11:14
solves your problem
```css
body {
  position: relative;
}
```

**Comment by andreash92** [comment] 2019-11-01 06:58
thanks to @pjominet's last answer i discovered the root of our problem which is somehow similar. 

In our project we are using a grid layout. To fix the problem i must set grid's height = 100%, but this is something that we should avoid due to our current layout

**Comment by andreash92** [comment] 2019-11-27 09:19
any workarounds without having to set the body height to 100% ?

**Comment by kailynnelson** [comment] 2020-01-03 23:24
We are looking for a similar solution in our own projects. 

`body { position: relative; }` does not help.

**Comment by slavede** [comment] 2020-02-25 15:57
I've opened PR that fixes this. Hopefully, it gets in asap and new version is tagged.

**Comment by slavede** [comment] 2020-02-28 08:50
To hopefully push this PR more quickly here's explanation why does it happen. Scenario when you don't have scrollbar on your body. When ng-select generating dropdown, it sets class to it which appears under the body and then body gets scrollbar. Then positioning is calculated as if body would have scrollbar, but then after setting position vertically this scrollbar dissapears and positioning is now wrong since scrollbar got away (this PR will handle it in a way that it hides scrollbar always whenever it's calculating position)

**Comment by tncho** [comment] 2020-03-10 14:47
Any idea on when this PR is getting released / merged? Thanks

**Comment by slavede** [comment] 2020-03-10 15:14
It's pending review for more than 10 days now. I see @varnastadeus is assigned.

**Comment by slavede** [comment] 2020-04-06 07:17
Does anyone know any other maintainer of this project expect @varnastadeus. He keeps ignoring messages and PR.

**Comment by andreash92** [comment] 2020-04-06 07:26
@slavede looks like @anjmao also maintains the project

**Comment by slavede** [comment] 2020-04-27 15:52
Here it is if you don't believe issue (it's forked example from official examples)

https://stackblitz.com/edit/angular-6c2svw?file=src%2Fbindings-default-example.component.ts

**Comment by RubenVermeulen** [comment] 2020-05-28 09:57
We're experiencing the same problem. Quite annoying. Would be great if a solution gets released.

**Comment by DepickereSven** [comment] 2020-06-23 15:16
There is a bigger problem when you update the width of your screen.

Let say you have a list with on top a search bar to search. Next to that search bar, you have a dropdown to sort your list based on a property you can select from that dropdown.

![image](https://user-images.githubusercontent.com/26543813/85420714-dce3bb00-b573-11ea-8a32-2fd414bf73a6.png)

The balk on the right represents the scrollbar. 


But if you search in your search bar your list will be filtered so the scrollbar will disappear 
![image](https://user-images.githubusercontent.com/26543813/85420910-1a484880-b574-11ea-9c16-87e784953a20.png)

So far no issue but when you open your dropdown you will see a mismatch in the UI

![](https://user-images.githubusercontent.com/16178577/67839985-882f9380-fafd-11e9-84c0-7458d19f1b94.jpg)


What is causing this mismatch? Well, this is all being calculated in the following function:

https://github.com/ng-select/ng-select/blob/9dae66b8859945427e056ef4e402f2d063c37fc5/src/ng-select/lib/ng-dropdown-panel.component.ts#L393-L403

The most important variable from this piece of code is `this._select` that variable is equal to the following variable:

https://github.com/ng-select/ng-select/blob/9dae66b8859945427e056ef4e402f2d063c37fc5/src/ng-select/lib/ng-dropdown-panel.component.ts#L133

That one again is equal to the following variable:

https://github.com/ng-select/ng-select/blob/9dae66b8859945427e056ef4e402f2d063c37fc5/src/ng-select/lib/ng-dropdown-panel.component.ts#L92

So what is going wrong, well that variable will never update, is that an issue?
Yes because when you have a scrollbar he will calculate the difference from the left side and add that to the dropdown elements.

https://github.com/ng-select/ng-select/blob/9dae66b8859945427e056ef4e402f2d063c37fc5/src/ng-select/lib/ng-dropdown-panel.component.ts#L394-L396
![image](https://user-images.githubusercontent.com/26543813/85421028-3b109e00-b574-11ea-8ebf-5411ef4142f0.png)


But when you have no scrollbar anymore because you filtered your list the variable that will calculate will not be updated. That is the issue because when the scrollbar disappears you will have more room on the left and that is causing the shift to the left.

![image](https://user-images.githubusercontent.com/26543813/85421667-fdf8db80-b574-11ea-876b-324937819c14.png)

**Comment by slavede** [comment] 2020-06-23 15:26
That's right, and my fix, fixes it. Well, here's PR https://github.com/ng-select/ng-select/pull/1601 (tests are failing, I'm under heavy fire on my regular job, so anyone can join the fix)

**Comment by DepickereSven** [comment] 2020-06-23 15:45
@slavede I placed a comment but I can't push to your branch to fix the test.

But your PR doesn't solve the issue that `this._dropdown.parentElement; ` doesn't update

**Comment by david-ding** [comment] 2020-07-26 13:21
Looks like the issue is when we appending the dropdown menu to another container, we are waiting for the dom element to be inserted before calculating the left offset. Problem with this is after appending the menu, it could have triggered the scrollbar to appear, and our left offset is calculated based on when scrollbar is shown. And after we re-positioned the menu, the scrollbar disappears and we end up with misaligned menu.

I've tried another approach - basically I separated updates to the X and Y offset, so that we calculate the left offset before appending the menu, and calculate the vertical offset after appending as usual, which seems to fix the issue.

I've also added event listener so it can react to window resize too.

**Closed** 2020-10-06 15:20 UTC
Labels: good for contribution, improvement

**Comment by gauravmasand09** [comment] 2021-03-07 16:39
Hi Everyone , was able to fix the issue y using **min-height:100vh** in my root div,
e.g -
```
<div class="container-fluid" style="min-height: 100vh;">
  <ng-container *ngIf="formLoaded; else loading">
    <div class="row">
      <div class="col-md-12">
        <ngb-accordion>
            <ngb-panel>
               ** here i am using form tag inside of form tag i am using ng-select **
            </ngb-panel>
        </ngb-according>
      </div>
    </div>
 </ng-container>
</div>
```

As u can see for my div 'container-fluid' from here my whole page starts so for this whole page i have given a min-height of 100vh this is what is rendered in my router-outlet so if u guys wanna use this in your root component tag u can use this property and it will work. Its working fine for me.
