### ISSUE TITLE
Highlight selection after search

### ISSUE THREAD

**Issue by mattx264** [ng-select/ng-select#920] opened 2018-11-05 20:08 UTC
**Describe the bug**
When you search for item by typing search criteria then select item, after click search box again it is not scrolling to selected item.

**To Reproduce** 
1. Go to https://ng-select.github.io/ng-select#/data-sources
2. Click on first dropdownlist (ng-select) component and type 'diann'
3. Select 'Diann Booker'
4. Click on ng-select component again

**Expected behavior**
Dropdown panel will scroll to selected item ('Diann Booker').

**Desktop**
 - Windows 10
 - Chrome
 -  70.0.3538.77

**Comment by varnastadeus** [comment] 2018-11-06 13:39
I think it is duplicate of #899

**Closed by varnastadeus** 2018-11-06 13:39 UTC
